### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Au-LiuJY** [kay-ck/GCMA#1]
Hi,dear author.I'm more than delighted to see your excellent work for open source.But how can I use you code to re-produce your great work?
Hoping that you can answer me soon and give me your guidance.Thanks!

**Comment by Au-LiuJY** [comment]
Hi

**Comment by kay-ck** [comment]
> Hi,dear author.I'm more than delighted to see your excellent work for open source.But how can I use you code to re-produce your great work? Hoping that you can answer me soon and give me your guidance.Thanks!

I'm sorry that my reply is a bit slow. Thank you for your attention to my work. If you want to reproduce my work, just run train.py after specifying --train_dir.
